from google.cloud import bigquery

client = bigquery.Client() # Initializing BigQuery client

# Define the dataset and table ID
project_id = 'arctic-column-432314-p8'
dataset_id = 'customer_profiles'
table_id = 'customer_data'

# Create a fully qualified dataset reference
dataset_ref = client.dataset(dataset_id, project=project_id)
table_ref = dataset_ref.table(table_id)

# Define schema based on the columns in your CSV
schema = [
    bigquery.SchemaField("appboy_ID", "STRING"),
    bigquery.SchemaField("campaign_Source", "STRING"),
    bigquery.SchemaField("city", "STRING"),
    bigquery.SchemaField("country", "STRING"),
    bigquery.SchemaField("dob", "TIMESTAMP"),
    bigquery.SchemaField("email", "STRING"),
    bigquery.SchemaField("gender", "STRING"),
    bigquery.SchemaField("language", "STRING"),
    bigquery.SchemaField("phone", "STRING"),
    bigquery.SchemaField("product", "STRING"),
    bigquery.SchemaField("source", "STRING"),
    bigquery.SchemaField("state", "STRING"),
    bigquery.SchemaField("address", "STRING"),
    bigquery.SchemaField("age", "STRING"),
    bigquery.SchemaField("age_group", "STRING"),
    bigquery.SchemaField("annual_revenue", "STRING"),
    bigquery.SchemaField("appraised_improvement_value", "STRING"),
    bigquery.SchemaField("interest_arts", "STRING"),
    bigquery.SchemaField("vehicle_year", "STRING"),
    bigquery.SchemaField("interest_cars", "STRING"),
    bigquery.SchemaField("benefits", "STRING"),
    bigquery.SchemaField("interest_boating", "STRING"),
    bigquery.SchemaField("interest_books", "STRING"),
    bigquery.SchemaField("browser", "STRING"),
    bigquery.SchemaField("browser_language", "STRING"),
    bigquery.SchemaField("browser_version", "STRING"),
    bigquery.SchemaField("campaign_name", "STRING"),
    bigquery.SchemaField("cancer_type", "STRING"),
    bigquery.SchemaField("car_accident", "STRING"),
    bigquery.SchemaField("car_insurance", "STRING"),
    bigquery.SchemaField("car_owner", "STRING"),
    bigquery.SchemaField("child_gender", "STRING"),
    bigquery.SchemaField("child_name", "STRING"),
    bigquery.SchemaField("clickid", "STRING"),
    bigquery.SchemaField("interest_collectibles", "STRING"),
    bigquery.SchemaField("connection_type", "STRING"),
    bigquery.SchemaField("interest_cooking", "STRING"),
    bigquery.SchemaField("country_code", "STRING"),
    bigquery.SchemaField("coverage_type", "STRING"),
    bigquery.SchemaField("credit_card_user", "STRING"),
    bigquery.SchemaField("credit_score", "STRING"),
    bigquery.SchemaField("custom_event", "STRING"),
    bigquery.SchemaField("days_visited", "STRING"),
    bigquery.SchemaField("deed_type", "STRING"),
    bigquery.SchemaField("delivery_validation", "STRING"),
    bigquery.SchemaField("description", "STRING"),
    bigquery.SchemaField("device", "STRING"),
    bigquery.SchemaField("device_brand", "STRING"),
    bigquery.SchemaField("device_browser", "STRING"),
    bigquery.SchemaField("device_model", "STRING"),
    bigquery.SchemaField("device_name", "STRING"),
    bigquery.SchemaField("device_os", "STRING"),
    bigquery.SchemaField("device_platform", "STRING"),
    bigquery.SchemaField("disabled", "STRING"),
    bigquery.SchemaField("doctor_treatment", "STRING"),
    bigquery.SchemaField("interest_charity", "STRING"),
    bigquery.SchemaField("education", "STRING"),
    bigquery.SchemaField("emailLastSeen", "TIMESTAMP"),
    bigquery.SchemaField("email_opt_out", "STRING"),
    bigquery.SchemaField("ethnicity", "STRING"),
    bigquery.SchemaField("everflow_id", "STRING"),
    bigquery.SchemaField("fax", "STRING"),
    bigquery.SchemaField("first_name", "STRING"),
    bigquery.SchemaField("first_visited_time", "STRING"),
    bigquery.SchemaField("first_visited_url", "STRING"),
    bigquery.SchemaField("interest_fitness", "STRING"),
    bigquery.SchemaField("food_wine_and_cooking", "STRING"),
    bigquery.SchemaField("fuel_type", "STRING"),
    bigquery.SchemaField("interest_gaming", "STRING"),
    bigquery.SchemaField("has_attorney", "STRING"),
    bigquery.SchemaField("has_cancer", "STRING"),
    bigquery.SchemaField("has_children", "STRING"),
    bigquery.SchemaField("interest_tech", "STRING"),
    bigquery.SchemaField("interest_gardening", "STRING"),
    bigquery.SchemaField("interest_home_improvement", "STRING"),
    bigquery.SchemaField("home_market_value", "STRING"),
    bigquery.SchemaField("home_value", "STRING"),
    bigquery.SchemaField("homeowner", "STRING"),
    bigquery.SchemaField("household_income", "STRING"),
    bigquery.SchemaField("household_size", "STRING"),
    bigquery.SchemaField("incident_date", "STRING"),
    bigquery.SchemaField("incomeRange", "STRING"),
    bigquery.SchemaField("industry", "STRING"),
    bigquery.SchemaField("injury_type", "STRING"),
    bigquery.SchemaField("interest_rate_type", "STRING"),
    bigquery.SchemaField("investing", "STRING"),
    bigquery.SchemaField("ip_address", "STRING"),
    bigquery.SchemaField("is_duplicate", "STRING"),
    bigquery.SchemaField("is_test_lead", "BOOLEAN"),
    bigquery.SchemaField("isp", "STRING"),
    bigquery.SchemaField("jornaya_cert", "STRING"),
    bigquery.SchemaField("keyword_searched", "STRING"),
    bigquery.SchemaField("landing_page", "STRING"),
    bigquery.SchemaField("last_name", "STRING"),
    bigquery.SchemaField("last_visited_time", "STRING"),
    bigquery.SchemaField("latestActivityDate", "TIMESTAMP"),
    bigquery.SchemaField("lead_id", "STRING"),
    bigquery.SchemaField("lead_source", "STRING"),
    bigquery.SchemaField("leads_payload_id", "STRING"),
    bigquery.SchemaField("lender_name", "STRING"),
    bigquery.SchemaField("length_of_residence", "STRING"),
    bigquery.SchemaField("luxury_vehicle_owner", "STRING"),
    bigquery.SchemaField("marital_status", "STRING"),
    bigquery.SchemaField("married", "STRING"),
    bigquery.SchemaField("medium", "STRING"),
    bigquery.SchemaField("interest_men_apparel", "STRING"),
    bigquery.SchemaField("mileage", "STRING"),
    bigquery.SchemaField("mortgage_amount", "STRING"),
    bigquery.SchemaField("mortgage_owner_type", "STRING"),
    bigquery.SchemaField("mortgage_refi_type", "STRING"),
    bigquery.SchemaField("mortgage_type", "STRING"),
    bigquery.SchemaField("interest_motorcycling", "STRING"),
    bigquery.SchemaField("interest_outdoors", "STRING"),
    bigquery.SchemaField("owner_occupancy", "STRING"),
    bigquery.SchemaField("interest_parenting", "STRING"),
    bigquery.SchemaField("percentage_asian", "STRING"),
    bigquery.SchemaField("percentage_black", "STRING"),
    bigquery.SchemaField("percentage_hispanic", "STRING"),
    bigquery.SchemaField("percentage_white", "STRING"),
    bigquery.SchemaField("interest_pets", "STRING"),
    bigquery.SchemaField("phone_type", "STRING"),
    bigquery.SchemaField("interest_politics", "STRING"),
    bigquery.SchemaField("prepaid", "STRING"),
    bigquery.SchemaField("product_name", "STRING"),
    bigquery.SchemaField("property_type", "STRING"),
    bigquery.SchemaField("random_bucket", "INTEGER"),
    bigquery.SchemaField("recording", "STRING"),
    bigquery.SchemaField("reference_no", "STRING"),
    bigquery.SchemaField("referral", "STRING"),
    bigquery.SchemaField("referral_url", "STRING"),
    bigquery.SchemaField("referrer", "STRING"),
    bigquery.SchemaField("region", "STRING"),
    bigquery.SchemaField("ringba_publisher_id", "STRING"),
    bigquery.SchemaField("ringba_publisher_name", "STRING"),
    bigquery.SchemaField("salutation", "STRING"),
    bigquery.SchemaField("second_vehicle_make", "STRING"),
    bigquery.SchemaField("second_vehicle_model", "STRING"),
    bigquery.SchemaField("second_vehicle_vin", "STRING"),
    bigquery.SchemaField("second_vehicle_year", "STRING"),
    bigquery.SchemaField("secondary_email", "STRING"),
    bigquery.SchemaField("interest_self_improvement", "STRING"),
    bigquery.SchemaField("senior_in_household", "STRING"),
    bigquery.SchemaField("session_count", "INTEGER"),
    bigquery.SchemaField("sex_abused", "STRING"),
    bigquery.SchemaField("single_parent", "STRING"),
    bigquery.SchemaField("skype_id", "STRING"),
    bigquery.SchemaField("sms_consent", "BOOLEAN"),
    bigquery.SchemaField("interest_sports", "STRING"),
    bigquery.SchemaField("status", "STRING"),
    bigquery.SchemaField("street_address", "STRING"),
    bigquery.SchemaField("street_name", "STRING"),
    bigquery.SchemaField("street_type", "STRING"),
    bigquery.SchemaField("suv_owner", "STRING"),
    bigquery.SchemaField("tax_amount", "STRING"),
    bigquery.SchemaField("telco", "STRING"),
    bigquery.SchemaField("title_company", "STRING"),
    bigquery.SchemaField("interest_travel", "STRING"),
    bigquery.SchemaField("trustedform_cert_url", "STRING"),
    bigquery.SchemaField("twitter", "STRING"),
    bigquery.SchemaField("unit_number", "STRING"),
    bigquery.SchemaField("us_veteran", "STRING"),
    bigquery.SchemaField("user_agent", "STRING"),
    bigquery.SchemaField("user_id", "STRING"),
    bigquery.SchemaField("interest_shopping", "STRING"),
    bigquery.SchemaField("vehicle_make", "STRING"),
    bigquery.SchemaField("vehicle_type", "STRING"),
    bigquery.SchemaField("vin", "STRING"),
    bigquery.SchemaField("visitor_score", "STRING"),
    bigquery.SchemaField("wealth_score", "STRING"),
    bigquery.SchemaField("website", "STRING"),
    bigquery.SchemaField("were_you_at_fault", "STRING"),
    bigquery.SchemaField("interest_women_apparel", "STRING"),
    bigquery.SchemaField("zip_code", "INTEGER"),
    bigquery.SchemaField("subscription_id", "STRING"),
    bigquery.SchemaField("subscription_state", "STRING"),
    bigquery.SchemaField("PAYLOAD", "JSON"),
    bigquery.SchemaField("created_at", "TIMESTAMP"),
    bigquery.SchemaField("updated_at", "TIMESTAMP")
]

# Create table with schema
table = bigquery.Table(table_ref, schema=schema)
table = client.create_table(table, exists_ok=True)

print(f"Table '{table_id}' created in dataset '{dataset_id}'.")
